import ccw_etl_library as ccw

import sys

import teradata

section=sys.argv[1]

# Volatile table for LCK #
lck = ccw.Statement(
    statement="""
CREATE VOLATILE TABLE V_LCK AS 
(
SELECT MAX(LOAD_CTL_KEY) LOAD_CTL_KEY
FROM ${ccw_view}.CCW_LOAD_CTL_STATS 
WHERE  PROJ_NM='${proj_nm}'
AND ETL_WRK_FOW_NM = 'base_clncl_case.py'
AND TRGT_TBLNM = 'CLNCL_CASE'
) WITH DATA PRIMARY INDEX (LOAD_CTL_KEY) ON COMMIT PRESERVE ROWS;
"""
)


# Volatile table for base clncl case #
base = ccw.Statement(
    statement="""
CREATE VOLATILE TABLE V_BASE_CLNCL_CASE AS
(
    SELECT
    CLNCL_CASE_KEY,
    CRET_TS,
    CHNL_SRC_CD,
    CHK_SUM_TXT
    FROM ${ccw_view}.CLNCL_CASE QUALIFY
    (ROW_NUMBER() OVER(PARTITION BY CLNCL_CASE_KEY ORDER BY CRET_TS DESC ))=1
WHERE CHNL_SRC_CD IN ('${chnl_src_cd}')
AND CURR_RCD_IND='Y'
)
WITH DATA PRIMARY INDEX (CLNCL_CASE_KEY) ON COMMIT PRESERVE ROWS;
   """
)

# Volatile table for base lookup #
baselkp = ccw.Statement(
    statement="""
CREATE VOLATILE TABLE V_BASE_LOOKUP AS
(
    SELECT
    STG.CLNCL_CASE_KEY
    ,STG.LOAD_CTL_KEY
    ,STG.CHNL_SRC_CD
    ,CASE WHEN BASE.CLNCL_CASE_KEY IS NULL THEN 'I'
    WHEN STG.CLNCL_CASE_KEY = BASE.CLNCL_CASE_KEY AND STG.CHK_SUM_TXT <> BASE.CHK_SUM_TXT THEN 'U' 
    WHEN STG.CURR_RCD_IND='N' THEN 'X' 
    END AS TRNSCTN_CD
    FROM ${ccw_stg}.CLNCL_CASE STG
    LEFT JOIN V_BASE_CLNCL_CASE BASE
    ON STG.CLNCL_CASE_KEY = BASE.CLNCL_CASE_KEY
    WHERE STG.CHNL_SRC_CD  IN('${chnl_src_cd}')
AND STG.LOAD_CTL_KEY IN (SELECT LOAD_CTL_KEY FROM V_LCK)
)WITH DATA PRIMARY INDEX (CLNCL_CASE_KEY) ON COMMIT PRESERVE ROWS;
   """
)
# delete unwanted volatile table #
deletevolatile = ccw.Statement(
    statement="""
DROP TABLE V_BASE_CLNCL_CASE;
  """
)


# Volatile table for base lookup #
updatebase = ccw.Statement(
    statement="""
UPDATE  A  FROM
${ccw_base}.CLNCL_CASE  A,
V_BASE_LOOKUP  B
SET
UPDT_TS = CURRENT_TIMESTAMP,
CURR_RCD_IND = 'N',
UPDT_LOAD_CTL_KEY = (SELECT LOAD_CTL_KEY FROM V_LCK)
WHERE
A.CLNCL_CASE_KEY = B.CLNCL_CASE_KEY
AND A.CHNL_SRC_CD = B.CHNL_SRC_CD
AND A.CHNL_SRC_CD IN ('${chnl_src_cd}')
AND A.CURR_RCD_IND = 'Y'
AND B.TRNSCTN_CD IN ( 'U','X');
"""
)

# Volatile table for base lookup #
insertbase = ccw.Statement(
    statement="""
INSERT INTO ${ccw_base}.CLNCL_CASE
(
CLNCL_CASE_KEY
,LOAD_CTL_KEY
,UPDT_LOAD_CTL_KEY
,CRET_TS
,UPDT_TS
,CHNL_CD
,CHNL_SRC_CD
,CHK_SUM_TXT
,CURR_RCD_IND
,CASE_ID
,CSM_ID
,ENTPR_CUST_ID
,CLNCL_CASE_MAST_KEY
,CUST_ELGBTY_ACCT_KEY
,CUST_CHNL_SRC_CD
,CLIENT_ID
,CLIENT_ACCT_NUM
,SRC_CUST_ID
,SRC_CASE_TY_CD
,CASE_TY_CD
,SRC_CLNCL_TY_CD
,CLNCL_TY_CD
,SRC_CASE_SUB_TY_CD
,CASE_SUB_TY_CD
,SRC_CASE_STAT_CD
,CASE_STAT_CD
,SRC_CASE_STAT_RSN_CD
,CASE_STAT_RSN_CD
,CASE_OPEN_TS
,CASE_CLS_TS
,SRC_ACUITY_CD
,ACUITY_CD
,SRC_TRTMT_INTSTY_LVL_CD
,TRTMT_INTSTY_LVL_CD
,SRC_PCPTN_CNSLTV_ACTY_CD
,PCPTN_CNSLTV_ACTY_CD
,GAP_INTRVNTN_IND
,SRC_STRTFCTN_LVL_CD
,STRTFCTN_LVL_CD
,SNMD_IND
,TRNSPLNT_IND
,SRC_PRIM_DIAG_CD
,PRIM_DIAG_CD
,SRC_PRIM_ICD_VRSN_CD
,PRIM_ICD_VRSN_CD
,CM_USR_ID
,CM_USR_KEY
,CM_ASGN_TS
,VRBL_CNSNT_TS
,CNSNT_OBTN_IND
,WRTN_CNSNT_TS
,SRC_SVC_INTRVL_NUM
,SRC_CRET_TS
,SRC_LAST_UPDT_TS
,CRET_BY_USR_KEY
,CRET_BY_USR_ID
,LAST_UPDT_BY_USR_ID
,LAST_UPDT_BY_USR_KEY
,BRND_EXPER_CD
,CNTRCT_LGL_ENTTY_CD
,DATA_RESTRCN_LVL_CD 
,AUTHZ_BY_USR_ID
,AUTHZ_BY_USR_KEY
,SRC_PRES_PROB_CD
,PRES_PROB_CD
)
SELECT
STG.CLNCL_CASE_KEY
,STG.LOAD_CTL_KEY
,STG.UPDT_LOAD_CTL_KEY
,CURRENT_TIMESTAMP AS CRET_TS
,STG.UPDT_TS
,STG.CHNL_CD
,STG.CHNL_SRC_CD
,STG.CHK_SUM_TXT
,STG.CURR_RCD_IND
,STG.CASE_ID
,STG.CSM_ID
,STG.ENTPR_CUST_ID
,STG.CLNCL_CASE_MAST_KEY
,STG.CUST_ELGBTY_ACCT_KEY
,STG.CUST_CHNL_SRC_CD
,STG.CLIENT_ID
,STG.CLIENT_ACCT_NUM
,STG.SRC_CUST_ID
,STG.SRC_CASE_TY_CD
,STG.CASE_TY_CD
,STG.SRC_CLNCL_TY_CD
,STG.CLNCL_TY_CD
,STG.SRC_CASE_SUB_TY_CD
,STG.CASE_SUB_TY_CD
,STG.SRC_CASE_STAT_CD
,STG.CASE_STAT_CD
,STG.SRC_CASE_STAT_RSN_CD
,STG.CASE_STAT_RSN_CD
,STG.CASE_OPEN_TS
,STG.CASE_CLS_TS
,STG.SRC_ACUITY_CD
,STG.ACUITY_CD
,STG.SRC_TRTMT_INTSTY_LVL_CD
,STG.TRTMT_INTSTY_LVL_CD
,STG.SRC_PCPTN_CNSLTV_ACTY_CD
,STG.PCPTN_CNSLTV_ACTY_CD
,STG.GAP_INTRVNTN_IND
,STG.SRC_STRTFCTN_LVL_CD 
,STG.STRTFCTN_LVL_CD
,STG.SNMD_IND
,STG.TRNSPLNT_IND
,STG.SRC_PRIM_DIAG_CD
,STG.PRIM_DIAG_CD
,STG.SRC_PRIM_ICD_VRSN_CD
,STG.PRIM_ICD_VRSN_CD
,STG.CM_USR_ID
,STG.CM_USR_KEY
,STG.CM_ASGN_TS
,STG.VRBL_CNSNT_TS
,STG.CNSNT_OBTN_IND
,STG.WRTN_CNSNT_TS
,STG.SRC_SVC_INTRVL_NUM
,STG.SRC_CRET_TS
,STG.SRC_LAST_UPDT_TS
,STG.CRET_BY_USR_KEY
,STG.CRET_BY_USR_ID
,STG.LAST_UPDT_BY_USR_ID
,STG.LAST_UPDT_BY_USR_KEY
,STG.BRND_EXPER_CD
,STG.CNTRCT_LGL_ENTTY_CD
,STG.DATA_RESTRCN_LVL_CD 
,STG.AUTHZ_BY_USR_ID
,STG.AUTHZ_BY_USR_KEY
,STG.SRC_PRES_PROB_CD
,STG.PRES_PROB_CD
FROM ${ccw_stg}.CLNCL_CASE STG
JOIN V_BASE_LOOKUP BASE_LKP
ON STG.CLNCL_CASE_KEY = BASE_LKP.CLNCL_CASE_KEY
WHERE STG.CHNL_SRC_CD  IN ('${chnl_src_cd}')
AND BASE_LKP.TRNSCTN_CD IN ('I','U');
   """
)


if __name__ == "__main__":

	# create a DB connection from the specified file
	db_connect = ccw.DatabaseConnection.from_config_file('/opt/utilities/clinical/clinical-base/etl_stg_base/python/common_lib/config/clncl_config.ini', section=section)
	
	# create a session
	db_connect.create_session()
	
	#begin ETL load process
	lck.execute(db_connect)
	base.execute(db_connect)
	baselkp.execute(db_connect)
	deletevolatile.execute(db_connect)
	updatebase.execute(db_connect)
	insertbase.execute(db_connect)
	# close your session
	db_connect.close_session() 